Command:
  # 各コマンドの使用権限
  Permission:
    imadonkurai: 0
    status: 0
    warp: 0
    walist: 0
    addwarp: 3
    delwarp: 3
    otu: 2
    kick: 2
    ban: 2
    black: 3
    rank: 3

  # 無効にするデフォルトコマンド
  Disable: |
    status

Jail:
  x: 0
  y: 100
  z: 0
  level: "lobby"

WarpList:
  test:
    x: 20
    y: 20
    z: 20
    level: "world"

